title: Shunx blog
description: Shunx Blog
remote_theme: just-the-docs/just-the-docs

url: https://shunianssy.github.io/shunx-blog

aux_links:
  Template Repository: https://github.com/shunianssy/shunx-blog

